### ISSUE TITLE
using mariadb jdbc driver in compose setup causes database to not be traced

### ISSUE THREAD

**Issue by driesdeproost** [xenit-eu/alfresco-zipkin#7]
using 
```
jdbc-driver:
    image: xeniteu/jdbc-mariadb:2.2.5
    volumes:
    - jdbc:/jdbc/
``` 
from [jdbc-drivers](https://github.com/xenit-eu/docker-jdbc-drivers) in `integration-tests/src/integration-test/resources/compose/docker-compose-mariadb.yml` causes the db to not be traced in zipkin. 
Alfresco works as normal though, so the db requests must be passing through the used P6SpyDriver. 

This bug does not happen if you use `xeniteu/jdbc-mysql:5.1.42` or a PG setup.
